---
title: "Application of NB ash (with fixed, large r) based on PG augmentation to some simulated count data"
author: "Yusha Liu"
date: "2020-10-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r warning=FALSE, message=FALSE}
library(ggplot2)
theme_set(theme_bw())
library(plyr)
library(dplyr)
library(reshape2)
source("code/util.R")

# grid of sigma2
sigma2 <- c(1e-6, 1e-5, 1e-4, 4e-4, 1e-3, 4e-3, 1e-2, 2e-2, 4e-2, 8e-2, 0.16, 0.32, 0.64, 1, 2, 4, 8, 16)

# specify the underlying mean for poisson (negative binomial) data
n = 1000 
w = 0.9
lambdasparse = rep(0,n)
for (i in 1:n)
{
  if(i<=round(n*w)){
    lambdasparse[i]<- 0.1
  }
  else {lambdasparse[i] <- 10}
}

```


### Scenario 1: poisson data 
```{r warning=F}
set.seed(786)
y <- rpois(n,lambdasparse) 

start_time = proc.time()
fit <- nb_ash_pg(y, sigma2, r=1000, init=NULL, maxiter=500, tol=1e-6, verbose=FALSE)
runtime = proc.time() - start_time
runtime

plot(fit$ELBO, xlab = "niter", ylab = "elbo")

fit$s2
fit$pi

r <- 1000
lambda.pm <- rowSums(fit$zeta * r * exp(fit$mu + fit$m + fit$v2/2))

post.data = rbind(data.frame(type = "true lambda", values=lambdasparse, x=seq(1:n)),
                  data.frame(type = "observation", values=y, x=seq(1:n)),
                  data.frame(type = "posterior mean", values=lambda.pm, x=seq(1:n)))

ggplot(post.data, aes(x=x, y=values, group=type, colour=type)) + 
  geom_point(aes(colour = type),size = 1) + ylab("Possion ash") + xlab(expression(y))+facet_grid(type~.,scales="free_y") + ylim(range(y))

```


### Scenario 2: negative binomial data (constant lambda, r=10)
```{r warning=F}
set.seed(100)
n = 1000 
y = rnbinom(n, size = 10, mu=10)

start_time = proc.time()
fit <- nb_ash_pg(y, sigma2, r=1000, init=NULL, maxiter=500, tol=1e-6, verbose=FALSE)
runtime = proc.time() - start_time
runtime

plot(fit$ELBO, xlab = "niter", ylab = "elbo")

fit$s2
fit$pi

r <- 1000
lambda.pm <- rowSums(fit$zeta * r * exp(fit$mu + fit$m + fit$v2/2))

post.data = rbind(data.frame(type = "true lambda", values=10, x=seq(1:n)),
                  data.frame(type = "observation", values=y, x=seq(1:n)),
                  data.frame(type = "posterior mean", values=lambda.pm, x=seq(1:n)))

ggplot(post.data, aes(x=x, y=values, group=type, colour=type)) + 
  geom_point(aes(colour = type),size = 1) + ylab("Possion ash") + xlab(expression(y))+facet_grid(type~.,scales="free_y") + ylim(range(y))

```


### Scenario 3: negative binomial data (sparse lambda, r=10)
```{r warning=F}
set.seed(500)
y = rnbinom(n, size=10, mu=lambdasparse)

start_time = proc.time()
fit <- nb_ash_pg(y, sigma2, r=1000, init=NULL, maxiter=500, tol=1e-6, verbose=FALSE)
runtime = proc.time() - start_time
runtime

plot(fit$ELBO, xlab = "niter", ylab = "elbo")

fit$s2
fit$pi

r <- 1000
lambda.pm <- rowSums(fit$zeta * r * exp(fit$mu + fit$m + fit$v2/2))

post.data = rbind(data.frame(type = "true lambda", values=lambdasparse, x=seq(1:n)),
                  data.frame(type = "observation", values=y, x=seq(1:n)),
                  data.frame(type = "posterior mean", values=lambda.pm, x=seq(1:n)))

ggplot(post.data, aes(x=x, y=values, group=type, colour=type)) + 
  geom_point(aes(colour = type),size = 1) + ylab("Possion ash") + xlab(expression(y))+facet_grid(type~.,scales="free_y") + ylim(range(y))

```